### ISSUE TITLE
app crashing with play -d package

### ISSUE THREAD

**Issue by DavidFaermanPendo** [1268/google#16]
ENV Mac M1 
./play -d com.google.android.youtube          

panic: field 6 is nil, not Raw

goroutine 1 [running]:
main.main()
	/Users/david.faerman/Projects/qmd/downloader/google/cmd/play/main.go:72 +0x5d8

other commands like
./play -d com.google.android.youtube -purchase
are not throwing anything (also not giving any response)
Thanks

**Comment by DavidFaermanPendo** [comment]
./play -d com.google.android.youtube -v 1537856960 worked and I was able to get the apk.
so looks like bringing the details is what is failing 
Thanks

**Comment by 1268** [comment]
I just tested this command and it works fine:

~~~
> play -d com.google.android.youtube
creator: Google LLC
file: APK APK APK APK
installation size: 90.55 megabyte
downloads: 14.41 billion
offer: 0 USD
title: YouTube
upload date: Jul 20, 2023
version: 18.29.33
version code: 1539034560
~~~

the software is free, but I only provide paid support. if you are interested let me know. otherwise good luck

**Comment by DavidFaermanPendo** [comment]
how much are we talking?

**Comment by 1268** [comment]
feel free to contact me:

https://github.com/1268/google#contact
