### ISSUE TITLE
Some apps won't download due to some missing params in /fdfe/delivery request

### ISSUE THREAD

**Issue by nutterthanos** [1268/google#25]
for example some apps/games need like the da parameter don't know if any other app/games needs any other parameter but com.ludia.jurassicworld needs the da parameter

**Comment by 1268** [comment]
I just tested and it works without `da` parameter

**Comment by 1268** [comment]
what commands did you run?

**Comment by nutterthanos** [comment]
play -s -t -d com.ludia.jurassicworld -v 2136017

**Comment by 1268** [comment]
the current code is correct, `da` is not needed. if you wish to pay for support let me know. otherwise good luck.

**Comment by nutterthanos** [comment]
how??
output is:
POST /auth HTTP/1.1
Host: android.clients.google.com
Content-Type: application/x-www-form-urlencoded

Token=REDACTED
GET /fdfe/delivery?doc=com.ludia.jurassicworld&vc=2136017 HTTP/1.1
Host: android.clients.google.com
Authorization: GoogleLogin auth=REDACTED
User-Agent: Android-Finsky (sdk=99,versionCode=80919999)
X-Dfe-Device-Id: REDACTED

panic: appDeliveryData

goroutine 1 [running]:
main.main()
        C:/Users/conno/google/cmd/play/main.go:78 +0x7d2

**Comment by 1268** [comment]
here is the output from the current code, with no edits to the code:

~~~
POST https://android.clients.google.com/auth
GET https://android.clients.google.com/fdfe/delivery?doc=com.ludia.jurassicworld&vc=2136017
GET https://play.googleapis.com/download/by-token/download?token=AOTCm0S04ydKTZ_ZVp5BZV86G5sefvuYDkZHROp3hx4MMXxo6lFuDtWJuGOk2M8GqKE2tlfxxCENqcW72cnedoL9H21vzP1cB6GOmJ7u1wlWsWg16irh7zNclj7ex-Bh5f9yQuwdxT-aZOiU4-EahHTDBK-zk70DNm-A3j_Lt7NORrVmzq42aq5ZKSgR_wuvZ3WcTkAPn0CdrZYgVy--YWbgv1-fANJsRREfe8bENfjMWKkdgrr1ewqkqAgUMPFjb8PfHBm5LRFu1I_KlEZ45JT7i9-MhFLAJxrU1NArFRRZ1dqSrAQPmtHMeau_4Xt6pmlkotZz_eSgD3d_fE-lMjnypvR5Hp4-n8HPmaNMPm3dojqdDuCdPGH62TnIiIs2iWDpsikAsz7yPQr1OyKCyz3m8ZuDpEwdZqsSHQeVLxBL3iYGOsv-iMGuIz_1x6oXpHzzsQ&cpn=X5sgBjYWhwNd9gA1
GET https://rr4---sn-q4fl6ndl.gvt1.com/play-apps-download-default/download/by-id/AF3DWBfkGpzLDiMDFxTo4XhicYUCStAldu_bYSMV_CIXaT0cwqUI3geu6pFBmjkVnGsP6kb1J_WXp9KP-mOahrgUIeT2Th8pHf8mhV4VZlhuI0e8jlfVRXm0ctjx4MkRvB852bpZtBai6JnttHbIAPPGhY94JmMbUg?cpn=X5sgBjYWhwNd9gA1&ctier=L&fvip=3&initcwndbps=1332500&mh=bO&mm=31,29&mn=sn-q4fl6ndl,sn-q4fzenee&ms=au,rdu&mt=1696286990&mv=m&mvi=4&pl=16&expire=1696460145&ip=72.181.23.38&ipbits=0&sparams=expire,ipbits,ip,q:,initcwndbps,mh,mm,mn,ms,mv,mvi,pl,ctier&signature=7337BCB0281E15ADC17AFDAB7FB75D4A4DE01713.2545B9FA00C556661480D4F439DA0EAB9EF68313&key=am3
~~~

If you are interested in paid support let me know, otherwise good luck.

**Comment by nutterthanos** [comment]
Then what am I doing wrong?
I already grabbed the game off of play store before using this

**Comment by 1268** [comment]
I have tried to make it very clear that I dont provide free support, but you dont seem to be getting it. good luck.
